version: '3.7'
services:
  cliqes_eventstore_node0:
    image: eventstore/eventstore
    container_name: cliqes-eventstore-node0
    restart: always
    ports:
      - 2113:2113
      - 1113:1113
    networks:
      cliqes_net:
        ipv4_address: 173.66.1.1
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
  cliqes_zookeeper_kafka:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      cliqes_net:
        ipv4_address: 173.66.1.10
  cliqes_kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      cliqes_net:
        ipv4_address: 173.66.1.20
networks:
  cliqes_net:
    ipam:
      driver: default
      config:
        - subnet: 173.66.0.0/16
